### ISSUE TITLE
ImportError: No module named speexdsp

### ISSUE THREAD

**Issue by coalboss** [xiongyihui/speexdsp-python#1]
运用sudo apt-get install libspeexdsp-dev 安装完依赖后，运用setup.py装上了，但好像无法使用，在terminal里使用ipython 无法import speexdsp 和from speexdsp import EchoCanceller ，但在用pycharm写一个.py时，import speexdsp似乎没有问题，但from speexdsp import EchoCanceller却不行，最后运行的时候会报错

**Comment by xiongyihui** [comment]
可能是运行的目录下面有个 speexdsp 的文件夹吧，python 会优先使用运行目录下的模块
