### ISSUE TITLE
fatal error: speex/speex_echo.h: No such file or directory

### ISSUE THREAD

**Issue by idealwhite** [xiongyihui/speexdsp-python#2]
您好，我尝试使用您的移植库时编译出现问题，看起来是因为我使用了python3的虚拟环境而系统的sudo执行环境之下的python是2.7，导致了编译的问题。但是如果如此，则说明安装python包的时候没有安装到虚拟环境之中。请问您有什么建议吗？

building 'speexdsp._speexdsp' extension
swigging src/speexdsp.i to src/speexdsp_wrap.cpp
swig -python -c++ -Isrc -o src/speexdsp_wrap.cpp src/speexdsp.i
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc -I/usr/include/python2.7 -c src/echo_canceller.cpp -o build/temp.linux-x86_64-2.7/src/echo_canceller.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
src/echo_canceller.cpp:6:30: fatal error: speex/speex_echo.h: No such file or directory
 #include "speex/speex_echo.h"
                              ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by xiongyihui** [comment]
没找到`speex/speex_echo.h`，是需要安装一下 libspeexdsp-dev

使用 sudo 的话，相当于新开了一个 root 的 shell，相当于跳出了前面的 python3 虚拟环境

python 3 是可以编译的，可以看 travis ci 的 log

https://travis-ci.org/xiongyihui/speexdsp-python/jobs/264577198#L478

**Comment by idealwhite** [comment]
已经编译通过，并且在虚拟环境中也成功安装，非常感谢！
