### ISSUE TITLE
Error about Type Error

### ISSUE THREAD

**Issue by TiranoGreatLand** [xiongyihui/speexdsp-python#3]
您好，我在使用EchoCanceller处理音频时，报出如下错误：
TypeError: in method 'EchoCanceller_process', argument 2 of type 'std::string const &'

我按照您目录里的test读取音频来处理，运行到
in_data = echo_canceller.process(in_data, out_data)
这一行代码时报出如上所示的错误。

**Comment by xiongyihui** [comment]
你应该是在用python3吧，刚添加了python3的bytes数据支持，升级一下应该可以用了。
