### ISSUE TITLE
LINK : fatal error LNK1181: 無法開啟輸入檔 'speexdsp.lib'

### ISSUE THREAD

**Issue by Jerry0103240** [xiongyihui/speexdsp-python#4]
Hello, I would like to try this library about echo cancellation,.
I don't really realize about the message, I can't find speexdsp.lib in my file, can you help me fix the problem?

Thanks a lot!!

I use visual studio 2017 and windows 10, python3.5
(Does it only work on Ubuntu or Linux environment ?!)

**Comment by xiongyihui** [comment]
I haven't try to build it on windows. The package depends on the speexdsp library, it is easy to install the speexdsp library on linux, but on windows, you need to built it by yourself.
The source of the speexdsp library is at https://github.com/xiph/speexdsp

**Comment by Jerry0103240** [comment]
Oh, I see. Thank you for replying me anyway!! I'll try another way to solve my problem.
