### ISSUE TITLE
Error about Makefile

### ISSUE THREAD

**Issue by changxuding** [xiongyihui/speexdsp-python#7]
您好，我用setup.py安装后没问题，但是用您写的Makefile编译后导入时会出现下面的错误：
>>> import speexdsp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lair/speexdsp-python/src/speexdsp.py", line 15, in <module>
    import _speexdsp
ImportError: /home/lair/speexdsp-python/src/_speexdsp.so: undefined symbol: PyInstance_Type
想请问以下您该怎么处理

**Comment by xiongyihui** [comment]
用的是python3吗？可能要把 Makefile 里面的 python-config 改成 python3-config

**Comment by changxuding** [comment]
您好，我用的是python3，更改后仍然报了一个错：
 ImportError: /home/lair/speexdsp-python/src/_speexdsp.so: undefined symbol: speex_echo_state_destroy
我这边libspeexdsp-dev安装了已经，而且编译过程中没有报错.

**Comment by changxuding** [comment]
编译成功了，谢谢您
